// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StBarnabasHospiceTable.Server.Data;

namespace StBarnabasHospiceTable.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210612171954_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StBarnabasHospiceTable.Shared.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "A cup of tea, drink. With or without milk and sugar.",
                            Image = "",
                            Name = "Tea"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The need to go to the bathroom and use the toilet.",
                            Image = "",
                            Name = "Toilet"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The need for some food and to eat.",
                            Image = "",
                            Name = "Food"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cat food.",
                            Image = "",
                            Name = "Pet Food"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kitty cat food.",
                            Image = "",
                            Name = "Kitty Cat Food"
                        });
                });

            modelBuilder.Entity("StBarnabasHospiceTable.Shared.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Columns")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("TableId");

                    b.HasIndex("ItemId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Columns = 3,
                            Rows = 3,
                            Title = "Common Items"
                        });
                });

            modelBuilder.Entity("StBarnabasHospiceTable.Shared.Table", b =>
                {
                    b.HasOne("StBarnabasHospiceTable.Shared.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
